-- migrate:up
CREATE TABLE users (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100)NOT NULL,
  USER_ID VARCHAR(100)NOT NULL,
  USER_PW VARCHAR(100)NOT NULL,
  PHONE_NUMBER VARCHAR(100) NULL
)

-- migrate:down
DROP TABLE users