-- migrate:up
CREATE TABLE driver (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100)NOT NULL,
  USER_ID VARCHAR(100)NOT NULL,
  USER_PW VARCHAR(100)NOT NULL,
  PHONE_NUMBER INT NOT NULL,
  CAR_NUMBER VARCHAR(100)NOT NULL
)

-- migrate:down
DROP TABLE driver