-- migrate:up
CREATE TABLE reservation (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  RESERVATION_DATE_TIME VARCHAR(100) NOT NULL,
  DEPARTURE_ADDRESS VARCHAR(200) NOT NULL,
  DEPARTURE_LAT DECIMAL(9,6) NOT NULL,
  DEPARTURE_LON DECIMAL(9,6) NOT NULL,
  DESTINATION_ADDRESS VARCHAR(200) NOT NULL,
  DESTINATION_LAT DECIMAL(9,6) NOT NULL,
  DESTINATION_LON DECIMAL(9,6) NOT NULL,
  USER_ID VARCHAR(100) NOT NULL,
  PAYMENT INT NOT NULL,
  RESERVATION_STATUS ENUM('예약 완료', '미완료') DEFAULT '미완료'
);

-- migrate:down
DROP TABLE reservation